Added lost steps

diff --git a/.github/workflows/check-base.yml b/.github/workflows/check-base.yml
--- a/.github/workflows/check-base.yml
+++ b/.github/workflows/check-base.yml
@@ -47,6 +47,23 @@ jobs:
 
       - name: Run Tests
         run: bundle exec fastlane ${{ matrix.lane }}
+
+      - name: Check Static Analyzer Output
+        id: analyzer-output
+        run: |
+          if [[ -z $(find ./derived_data -name "report-*.html") ]]; then
+            echo "Static Analyzer found no issues."
+          else
+            echo "Static Analyzer found some issues. HTML report will be available in Artifacts section. Failing build."
+            exit 1
+          fi
+      
+      - name: Static Analyzer Reports Uploading
+        if: ${{ failure() && steps.analyzer-output.outcome == 'failure' }}
+        uses: actions/upload-artifact@v2
+        with:
+          name: static-analyzer-reports-${{ matrix.lane }}
+          path: ./derived_data/**/report-*.html
       
       # This is the script specified as the pod’s prepare_command in its Podspec.
       # It would be run automatically for a normal CocoaPods install, but it doesn’t
