Changed directory to `build`

diff --git a/.github/workflows/check.yml b/.github/workflows/check.yml
--- a/.github/workflows/check.yml
+++ b/.github/workflows/check.yml
@@ -59,12 +59,11 @@ jobs:
       
       - name: Check Static Analyzer Output
         run:  |
-          if [[ -z `find clang -name "*.html"` ]]; then
-            echo "Static Analyzer found no issues. Fail for demo purpose."
-            exit 123
+          if [[ -z `find build -name "*.html"` ]]; then
+            echo "Static Analyzer found no issues."
           else
-            echo "Static Analyzer found some issues"
-            exit 1234
+            echo "Static Analyzer found some issues. Failing build."
+            exit 1
           fi
 
       # This is the script specified as the pod’s prepare_command in its Podspec.
